metadata:
  generateName: terraform-example
  namespace: argo
spec:
  entrypoint: update
  arguments:
    parameters:
    - name: terraform-script-repository
      value: "http://167.233.12.7:30165/sokuyucu/terraform-kae.git"
# TEMPLATES
# UPDATE manages the flow by calling other templates like functions
  templates:
  - name: update
    steps:
    - - name: generate-ssh
        template: key-gen
    - - name: apply
        template: apply
        arguments:
          artifacts:
          - name: keys
            from: "{{steps.generate-ssh.outputs.artifacts.keys}}"

# KEY-GEN generates ssh-keys
  - name: key-gen
    container:
      image: hashicorp/terraform:latest
      command: [sh,-c]
      args: ["mkdir /home/key-pairs && ssh-keygen -t rsa -N '' -f /home/key-pairs/id_rsa"]
    outputs:
      artifacts:
      - name: keys
        path: /home/key-pairs/

# APPLY terraform initialization and application, requires ssh keys
  - name: apply
    inputs:
      artifacts:
      - name: keys
        path: /home/ssh-keys
      - name: terraform
        path: /home/terraform
        git:
          repo: "{{workflow.parameters.terraform-script-repository}}"
          depth: 1
    container:
      image: hashicorp/terraform:latest
      command: [sh, -c]
      args: ["/bin/terraform init /home/terraform && echo yes | /bin/terraform apply /home/terraform"]
